version: 2.1

orbs:
  node: circleci/node@1.1.6
  terraform: ovotech/terraform@1.6.6
  docker: circleci/docker@1.0.1

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: josephnp732/movie-api
          tag: latest
      - docker/push:
          image: josephnp732/movie-api
          tag: latest

workflows:
  build-and-deploy:
    jobs:
      - build-and-test
      - build-and-push:
          requires:
            - build-and-test